In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

In [2]:
# similar movies on the bases of

# 0- overall
# 1- scale (revenue and budget)
# 2- story (genre and story)
# 3- crew and cast


# algos-
# kmeans clustering
# heireical clustering
# dbscan

# story

In [3]:
df = pd.read_csv("../data/interim/story.csv")

In [4]:
df.shape

(9903, 643)

In [5]:
df.drop(["Unnamed: 0", "poster_path"], axis=1, inplace=True)

In [6]:
df.head(1)

,adult,budget,id,origin_country,original_language,popularity,production_companies,production_countries,revenue,runtime,...,wife_over,win_over,with_over,woman_over,women_over,work_over,world_over,year_over,york_over,young_over
0,False,45000000.0,1011477,['US'],en,750.3586,"[{'id': 5, 'logo_path': '/71BqEFAF4V3qjjMPCpLu...","[{'iso_3166_1': 'US', 'name': 'United States o...",104560790,94,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.216504,0.0

In [7]:
story = df.drop(
    [
        "budget",
        "adult",
        "id",
        "credits",
        "origin_country",
        "revenue",
        "cast",
        "crew",
        "production_companies",
        "popularity",
        "status",
        "title",
        "video",
        "vote_average",
        "vote_count",
        "hit/flop",
        "profit_per",
        "box-off",
        "runtime",
        "original_language",
        "production_countries",
        "spoken_languages",
    ],
    axis=1,
)

In [8]:
story.shape

(9903, 619)

In [9]:
X = story.values

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(X)


def Recommend(movie):
    index = df[df["title"] == movie].index
    curr = similarity[index]
    top5 = np.argsort(curr)[0, :][::-1][1:6]
    return df[df.index.isin(top5)]["title"]


Recommend("Avatar")

1991    The Wandering Earth II
3442            Monster Hunter
4464            Monster High 2
7851          Heavy Metal 2000
9883                     Krull
Name: title, dtype: object

In [11]:
import pickle

with open("../models/story.pkl", "wb") as f:
    pickle.dump(similarity, f)

# Cast and crew

In [39]:
df = pd.read_csv("../data/interim/cast.csv")

In [72]:
df.head(1)

,adult,budget,genres,id,origin_country,original_language,original_title,overview,popularity,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,credits,keywords,box-off,hit/flop,profit_per,release_year,release_day,release_month,Universal Pictures,Warner Bros. Pictures,Columbia Pictures,Paramount Pictures,20th Century Fox,Walt Disney Pictures,Metro-Goldwyn-Mayer,New Line Cinema,Lionsgate,TOHO,Relativity Media,StudioCanal,DreamWorks Pictures,Vivamax,Summit Entertainment,United Artists,Working Title Films,Touchstone Pictures,Regency Enterprises,Village Roadshow Pictures,Miramax,TSG Entertainment,Amblin Entertainment,Blumhouse Productions,Warner Bros. Animation,DreamWorks Animation,dentsu,Canal+,Ingenious Media,Focus Features,TriStar Pictures,TF1 Films Production,Imagine Entertainment,Screen Gems,Legendary Pictures,Dune Entertainment,Millennium Media,Film4 Productions,Nippon Television Network Corporation,Original Film,Toei Animation,CJ Entertainment,New Regency Pictures,Fox 2000 Pictures,Dimension Films,Orange Sky Golden Harvest,Shogakukan,Constantin Film,DC Entertainment,FilmNation Entertainment,United States of America,United Kingdom,France,Japan,Canada,South Korea,Germany,India,Italy,Hong Kong,China,Spain,Australia,Belgium,Philippines,Mexico,Sweden,Indonesia,Ireland,Denmark,Russia,Netherlands,Switzerland,Thailand,Brazil,Poland,Norway,Taiwan,Argentina,New Zealand,South Africa,Turkey,Czech Republic,Finland,Luxembourg,Bulgaria,Hungary,Greece,Austria,Colombia,United Arab Emirates,Serbia,Romania,Iceland,Chile,Soviet Union,Singapore,Peru,Israel,Morocco,Frank Welker,Samuel L. Jackson,Fred Tatasciore,Robert De Niro,Jackie Chan,Nicolas Cage,Bruce Willis,Liam Neeson,Willem Dafoe,Min Do-yoon,Jim Cummings,Ikue Otani,Megumi Hayashibara,Matt Damon,Morgan Freeman,Koichi Yamadera,J.K. Simmons,Dee Bradley Baker,Tom Hanks,Jess Harnell,Michael Papajohn,Kappei Yamaguchi,Jeff Bennett,Tara Strong,Johnny Depp,Steve Buscemi,Adam Sandler,Grey DeLisle,Kevin Michael Richardson,Sylvester Stallone,Thomas Rosales Jr.,Scarlett Johansson,John Leguizamo,Brad Pitt,Keanu Reeves,Stephen Root,Jason Statham,Bill Murray,Mark Wahlberg,Laurence Fishburne,John DiMaggio,Bob Bergen,Woody Harrelson,Tom Cruise,John Goodman,Stanley Tucci,Bill Hader,Danny Trejo,Kari Wahlgren,Keith David,Gary Oldman,Antonio Banderas,Idris Elba,Jack Black,Laraine Newman,Channing Tatum,Arnold Schwarzenegger,Dwayne Johnson,Toby Jones,Scott Menville,Cate Blanchett,Stan Lee,Alec Baldwin,Nicole Kidman,Tom Kenny,Brian Cox,Owen Wilson,Alan Tudyk,Ving Rhames,Harrison Ford,Ryan Reynolds,Seth Rogen,Peter Stormare,Michael Caine,Mickie McGowan,Carlos Alazraqui,Wataru Takagi,Bill Farmer,Richard Jenkins,Joe Chrest,Rob Paulsen,Bradley Cooper,Ralph Fiennes,Dennis Quaid,Denzel Washington,Elizabeth Banks,Danny Mann,Anthony Hopkins,Donald Sutherland,Scott Adkins,Ben Affleck,John Malkovich,Will Ferrell,Chris Evans,Robert Duvall,Michael Shannon,Jason Isaacs,Ben Kingsley,Kevin Hart,Robin Williams,Mel Gibson,Tress MacNeille,Ken Jeong,Sigourney Weaver,Dustin Hoffman,Paul Rudd,Clancy Brown,Jack Angel,Colin Farrell,Shin-ichiro Miki,Paul Giamatti,Gerard Butler,Anthony Mackie,Benedict Cumberbatch,Kevin Costner,Ed Harris,Luis Guzmán,Ron Perlman,John Travolta,Rikiya Koyama,Eddie Marsan,Ben Stiller,Mayumi Tanaka,Unsho Ishizuka,Charlize Theron,Jeff Goldblum,Michael Peña,Zoe Saldaña,Phil LaMarr,Anne Hathaway,John Lithgow,Djimon Hounsou,Bill Nighy,Mark Strong,John Hurt,Josh Brolin,Will Smith,Corey Burton,Debi Derryberry,Sherry Lynn,Lee Chae-dam,Maya Rudolph,George Clooney,John C. Reilly,Jonah Hill,John Ratzenberger,Brendan Gleeson,Jude Law,Russell Crowe,Joseph Gordon-Levitt,Forest Whitaker,Jamie Foxx,Alfred Molina,Rob Schneider,Michael Keaton,Tomokazu Seki,Kazuhiko Inoue,Julia Roberts,Pierce Brosnan,Robin Atkin Downes,Viola Davis,Gene Hackman,Michelle Yeoh,Christian Bale,Keegan-Michael Key,Lucy Liu,Octavia Spencer,James Franco,Salma Hayek Pinault,Danny DeVito,William H. Macy,Jean-Claude Van Damme,Ethan Hawke,Dan Aykroyd,Rosario Dawson,Susan Sarandon,Michael Rooker,Shea Whigham,Jon Favreau,Matthew McConaughey,Robert Downey Jr.,John Cleese,Tilda Swinton,Helena Bonham Carter,Emma Thompson,Eddie Murphy,Julianne Moore,Clint Eastwood,James Earl Jones,Jackie Sandler,Allison Janney,Danny Glover,Jet Li,Ritchie Montgomery,Chris Pratt,James Marsden,Steve Carell,Bryan Cranston,Stellan Skarsgård,Rodger Bumpass,David Thewlis,Yuki Kaji,Kurt Russell,Patrick Wilson,Phil Proctor,Lin Shaye,Ciarán Hinds,Terry Crews,Meryl Streep,Angelina Jolie,Bobby Cannavale,Ewan McGregor,Tommy Lee Jones,Jennifer Lopez,Minami Takayama,Kenichi Ogata,John Michael Higgins,Jon Bernthal,Kristen Wiig,Hugh Jackman,Dave Bautista,James Hong,Chris Hemsworth,Kathy Bates,Christopher Walken,Amy Adams,Jim Broadbent,Marisa Tomei,Sandra Bullock,Danny Huston,Jake Gyllenhaal,Cameron Diaz,Jeremy Irons,Greg Bronson,Anna Kendrick,Bridget Hoffman,Jason Bateman,Rance Howard,Chris Cooper,Patrick Warburton,Luke Wilson,Billy Slaughter,Steve Zahn,Frank Grillo,Simon Pegg,Cary Elwes,Sam Neill,Tim Blake Nelson,Giancarlo Esposito,James Cromwell,Brad Garrett,Mark Ruffalo,Helen Mirren,William Fichtner,Joan Cusack,Jean Reno,Cheech Marin,Whoopi Goldberg,Jonathan Loughran,Michelle Pfeiffer,Vince Vaughn,Allen Covert,Thomas Lennon,Patrick Stewart,Clifton Collins Jr.,Tony Shalhoub,Naomi Watts,Wakana Yamazaki,Masako Nozawa,Christopher McDonald,John Cena,Carla Gugino,Vin Diesel,Holt McCallany,Jason Flemyng,Johnny Otto,Christopher Mintz-Plasse,Ralph Ineson,Harry Dean Stanton,Don Cheadle,Jeffrey Tambor,Akio Otsuka,Michael Gambon,Edward Norton,John Turturro,Cliff Curtis,Clint Howard,Xander Berkeley,Harvey Keitel,Sven-Ole Thorsen,Guy Pearce,David Cowgill,Judi Dench,Dermot Mulroney,Anthony Molinari,Chafurin,Emma Stone,Glenn Close,Thomas Kretschmann,Molly Shannon,Philip Seymour Hoffman,John Cusack,David Koechner,Roy Beck,Queen Latifah,Justin Long,Kevin Bacon,Sean Connery,Bruce Greenwood,Colleen Camp,Anjelica Huston,Uma Thurman,Al Pacino,Jennifer Coolidge,Nick Offerman,Angela Bassett,Jim Carrey,Vincent D'Onofrio,Jeffrey Wright,Leonardo DiCaprio,Bill Paxton,Emily Blunt,Matt Walsh,John Franchi,Vincent Cassel,Kevin Spacey,Rose Byrne,Cuba Gooding Jr.,Kirsten Dunst,Michael Douglas,Toshiyuki Morikawa,Hugh Grant,Liev Schreiber,David Cross,Arthur Tovey,Tom Wilkinson,Dean Norris,J.D. Evermore,Kotono Mitsuishi,Laura Dern,Judy Greer,Gary Weeks,Frank Oz,Benicio del Toro,Jennifer Garner,Maggie Smith,Warwick Davis,Donnie Yen,Kate Winslet,Kath Soucie,James Remar,Christopher Lee,Marion Cotillard,Oscar Isaac,Jason Schwartzman,Rob Riggle,Giovanni Ribisi,Natalie Portman,Jon Voight,Will Arnett,Kristen Bell,Mona Marshall,Chris Rock,Blake Clark,Sam Rockwell,Seth Green,Jamie Lee Curtis,Ben Mendelsohn,Chloë Grace Moretz,Eugene Levy,Dennis Haysbert,Ray Liotta,Dolph Lundgren,Richard Riehle,Daniel Craig,Leslie Mann,James Woods,Tim Curry,Naoko Matsui,Kazuya Nakai,Ryo Horikawa,Kevin Dunn,Nicholas Hoult,Chiwetel Ejiofor,Sebastian Stan,David Harbour,Tony Todd,Mark Hamill,Catherine O'Hara,Andy Serkis,Steve Blum,Steve Coulter,Viggo Mortensen,Hugo Weaving,Peter Dinklage,Robert Tinsley,Val Kilmer,Jennifer Connelly,James McAvoy,Timothy Spall,Andy Samberg,Chris Pine,Conrad Vernon,Jeff Bridges,Common,Kristen Stewart,Patton Oswalt,Michelle Monaghan,Will Forte,Christopher Plummer,Colin Firth,Mars,Robert Patrick,Anna Faris,Frances McDormand,Nick Nolte,Yukiko Iwai,Miyuki Sawashiro,Ian McShane,Zach Galifianakis,Sean Bean,Demi Moore,Jeremy Renner,Sang Woo,Thomas Haden Church,Robin Wright,Jonathan Pryce,Debra Wilson,Drew Barrymore,P.J. Byrne,Rachel McAdams,John Cho,Halle Berry,John Carroll Lynch,Sunny Sandler,Joaquin Phoenix,Chris Ellis,Seann William Scott,Michael Fassbender,Andy García,John Cenatiempo,Jesse Plemons,Kang Min-woo,Nick Swardson,Lance Henriksen,Jessica Alba,Philip Baker Hall,Rachel Weisz,Christopher Lloyd,Christian Slater,Hank Azaria,Ken Lo,Melissa McCarthy,Kimberly Brooks,Winona Ryder,M. Emmet Walsh,Jennifer Aniston,Catherine Keener,Kiefer Sutherland,Zac Efron,Billy Bob Thornton,Toby Huss,Chris Parnell,Kevin Pollak,Charlie Sheen,Jack McGee,Sean Penn,Olga Kurylenko,Adrian Martinez,Taraji P. Henson,Peter Jason,Cillian Murphy,Tom Hardy,Gwyneth Paltrow,Paul Bettany,Alan Rickman,Ray Winstone,Michael Madsen,Colm Meaney,Aaron Eckhart,Fred Armisen,Keira Knightley,Sam Worthington,Bruce Campbell,Kevin James,Maurice LaMarche,Charles Dance,Max von Sydow,Shia LaBeouf,David Spade,Richard Kind,Dennis Keiffer,Bill Camp,Cedric the Entertainer,Stephen Tobolowsky,Neal McDonough,Simon Rhee,Reese Witherspoon,Bruce Dern,Missi Pyle,Barbara Harris,Dan O'Connell,Gary Burritt,Mary Vernieu,John T. Cucci,Mo Henry,Thomas J. O'Connell,Peter Burgis,John Roesch,Randy Thom,Chris Navarro,Gary Archer,Doug Coleman,Robert Rodriguez,G.A. Aguilar,Hans Zimmer,Glenn Freemantle,Jim Passon,Steven Spielberg,Christopher Boyes,Jimmy N. Roberts,Nerses Gezalyan,Joe Bucaro III,James Ashwill,Debbie Evans,Skip Lievsay,Doc Kane,Bob Weinstein,Harvey Weinstein,Mark DeSimone,Francine Maisler,Jeff 'JJ' Dashnaw,Clay Cullen,Luc Besson,Peter Epstein,Kevin O'Connell,Andy Nelson,Jack Gill,Sarah Halley Finn,Gary A. Hecker,John Papsidera,Troy Robinson,John C. Meier,Michael Miller,Howard London,Gary Rydstrom,Arnon Milchan,Anna Behlmer,Chris Palermo,Blaise Corrigan,Pat Romano,Marko Costanzo,Paul Massey,Pete Anthony,Rick Avery,Hans Bjerno,Melissa R. Stubbs,Steve Kelso,Glen Gathard,Charlie Picerni,Dennie Thorpe,James Newton Howard,Henry Kingi,Matt Curtis,Gregory J. Barnett,Alan Silvestri,Jeff Imada,Jana Vance,Mic Rodgers,Terry Leonard,J.J. Perry,Mickey Giacomazzi,Peter Gleaves,Annie Ellis,Charleen Richards-Steeves,Al Goto,Ethan Van der Ryn,Andy Gill,Lora Hirschberg,Chris Lyons,Michael Hatzer,Alyson Dee Moore,Chris Scarabosio,Avy Kaufman,Danny Wynands,Bob Brown,Dick Ziker,Randy K. Singer,Jalil Jay Lynch,David B. Nowell,Tim Trella,Michael Runyard,John Debney,Michael Semanick,Robin Harlan,Deborah Aquila,Chris Cenatiempo,David Leitch,Sarah Monat,Lance Gilbert,Mike Prestwood Smith,Marco Beltrami,Jason Blum,Aaron Vexler,Erik Aadahl,Steve M. Davison,John Williams,Danny Elfman,Jerry Goldsmith,Tim Bevan,James Horner,Alicia Stevenson,Darrin Prescott,Ron Bartlett,Gary Rizzo,Craig Henighan,Eric Fellner,Mark De Alessandro,Greg Steele,Stefan Sonnenfeld,Jeanne McCarthy,Tricia Wood,Greg P. Russell,Richard King,Aaron Becker,Nina Gold,David Lucarelli,Keith Woulard,Steven Soderbergh,Michelle Pazer,Buddy Joe Hooker,Greg Orloff,Troy Brown,Christopher Flick,Doug Hemphill,Eliza Coleman,Caitlin McKenna,Bruce Berman,Toby Emmerich,Robert Alonzo,Vic Armstrong,Richard Epper,Tommy J. Huff,Billy D. Lucas,Greg Powell,Spiro Razatos,Shawnna Thibodeau,Christopher Assells,Owen Walstrom,Chuck Picerni Jr.,Randall Poster,Dane Farwell,Will Files,Zack Duhame,Roy Farfel,Troy Gilbert,Henry Kingi Jr.,Geoffrey Haley,Allan Graf,Christophe Beck,Tony Lamberti,Dave Jordan,Michael Babcock,Alexander Witt,Joey Box,Allan Padelford,Leslie Shatz,Goro Koyama,Charles Croughwell,Conrad E. Palmisano,Andrew Rowlands,Juan Peralta,Mark Mangini,Denney Pierce,Freddie Hice,Lewis Goldstein,Ronna Kress,Gregg Landaker,Jennifer Badger,Garrett Warren,Dawn Fintor,Michael Minkler,Dino DiMuro,Richard Brener,Scott Wilder,Frank A. Montaño,Andy Malcolm,Krista Bell,Mary Jo Lang,Chad Stahelski,James Wan,Terri Taylor,Chris O'Hara,David James,Donna Evans,Janet Brady,Scott Curtis,Casey O'Neill,Denise Chamian,Derek Casari,James Moriana,Gregg Rudloff,Catherine Harper,Boaz Davidson,Roy Lee,Hank Amos,Jill Brown,Adam Somner,John Morris,Michael Hertlein,Joel Coen,Ethan Coen,Frank Marshall,Alexandre Desplat,Jack Kirby,Tim Rigby,Manny Perry,Norman Howell,George Doering,Mark Southworth,Keith Campbell,Tom Elliott,Carter Burwell,Jack Stew,Scott Millan,Rick Kline,Scott Rudin,Dan Bradley,Rich Delia,Tom Myers,Levan Doran,Brian Tyler,Jeffrey Wilhoit,John Davis,Stephen King,Jane Jenkins,Tom Johnson,David Newman,Brian Smrz,Nancy Nayor,Robert Troy,Jason Swanscott,Avi Lerner,Heidi Moneymaker,Mark Taylor,Lorne Balfe,Rowley Irlam,Dane A. Davis,Guillermo del Toro,Drew Jones,Kerry Barden,David Lee,John T. Reitz,Mike Smith,Ellen Heuer,Debra Zane,Mark Gordon,John Powell,Gwendolyn Yates Whittle,Steve Boeddeker,Janet Hirshenson,James Cameron,Gary Summers,Brian Grazer,David Betancourt,Wylie Stateman,Jeremy Fry,Robert Zemeckis,Paul E. Short,Gilbert B. Combs,John Carpenter,Danny Epper,Yvan Lucas,Shauna Duggins,Marc Wolff,Ai-Ling Lee,Howard Shore,Ridley Scott,Amanda Mackey,Tad Griffith,Ray McIntyre Jr.,John Hughes,Paul Urmson,Donah Bassett,John Frazier,Michael Giacchino,Robert Jackson,Simon Crane,George Lucas,Rick Canelli,Bruce Tanis,Tim Chau,John Lasseter,Jennifer Caputo,Cristian Knight,Louis D'Esposito,Neal H. Moritz,Mindy Marin,Willie D. Burton,Bill R. Dean,Bill Corso,Steve Baine,Melinda Sue Gordon,Terry Jackson,Alexander Courage,Terry Porter,Peter Staubli,Kenny Bates,Chris Jargo,Hector C. Gika,Greg Zimmerman,Anne McCarthy,Jon Title,Michael J. Benavente,Peter Bucossi,Sam Register,Erik Rondell,Jason W. Jennings,David Giammarco,Joni Avery,Russell Farmarco,Caroline Vexler,Jerad Marantz,Joel Silver,Kenny Endoso,Steve Maslow,Bobby Johanson,Tony Brubaker,Robert Simonds,George Cottle,Daniel Laurie,Shannon Mills,Brad Martin,Michael Byrch,David Appleby,Jodi Michelle Pynn,Marny Eng,Cathy Sandrich Gelfond,Scott Martin Gershin,Oakley Lehman,Randall Balsmeyer,Scott J. Ateah,Jeannie Epper,Makoto Shinkai,Michael Kamen,Hideaki Anno,Jina Jay,Tyler Perry,Carmen Cuba,Pete Ford,Mallory Thompson,Jung Do-ahn,Josh McLaglen,George Richmond,Shawn Murphy,Teresa Eckton,Noon Orsatti,Dennis Sands,David Orr,Pete Romano,Lindsay Graham Ahanonu,George A. Lara,Mike Fenton,Michael Bay,Corey Michael Eubanks,Dan Perri,Craig Berkey,Robert Fernandez,James M. Halty,Lisa Hoyle,Jeremy Braben,Todd Harris,Armen Ksajikian,John C. Stuver,Jennifer Lamb,Jason Oliver,Thomas Robinson Harper,Billy Hopkins,Martin Scorsese,Terri Douglas,Colin Anderson,Becky Sullivan,Danny Rogers,Tracey Wilson,Zoe Freed,Jeff Habberstad,David V. Butler,R.A. Rondell,Jo McLaren,Francis Ford Coppola,Holly Sedillos,Ben Scott,Tim Gomillion,David Jobe,Michael De Luca,Chris Jenkins,John Marzano,Susan Dudeck,Ryan Kavanaugh,Jeff Carson,Lauro David Chartrand-DelValle,Niv Adiri,Gosho Aoyama,Ben Cooke,Kevin Feige,Sarah Lochlan,James Thatcher,Harry Cohen,Laura Lee Connery,Debbie Lynn Ross,Ron Howard,Tom Brown,Kathleen Kennedy,Gary McLarty,Thomas Newman,Brian Avery,Howard Berger,Gregg Barbanell,Dan Hegeman,Ve Neill,Dale E. Grahn,Joseph P. Reidy,Trevor Short,Gene LeBell,Hiroyuki Horiuchi,Annabel Wood,Cliff Fleming,Cliff Lanning,Gene Hartline,Kimberly Shannon Murphy,Mark Norby,David R. Ellis,Matthew Harrison,Laura Albert,Hilda Hodges,George B. Colucci Jr.,Tom Fleischman,Victoria Thomas,Graeme Revell,Matt Leonard,Chuck Finch,David C. Hughes,Darrin Mann,Tim Wooster,Shelley Roden,Kevin Kaska,Al Cerullo,Scott Rogers,Donald Mowat,Stephen S. Campanelli,Karen Baker Landers,Kwak Tae-yong,Lane Leavitt,Adam Shankman,Tom Ozanich,Ennio Morricone,Bill Anagnos,Chris Carpenter,Roger Birnbaum,Doug Jackson,Liza Chasin,Judd Apatow,Lucy Bevan,Luke Tumber,Ren Klyce,Don Lee,Lee Gilmore,Tammy Fearing,Daniel W. Barringer,Stephen A. Pope,Harry Gregson-Williams,Bob Badami,Patrick Tatopoulos,Michael Keller,David Boulton,Beau Borders,Sam Raimi,Joel Kramer,Philip Stockton,Quentin Tarantino,Per Hallberg,Janet Paparazzo,Jeff Sanca,Mark Isham,Greg Nicotero,Gregg Smrz,Ellen Chenoweth,Chick Bernhard,Patrick J. Foley,Aja Frary,Rafael E. Sánchez,Al Nelson,Gary Powell
0,False,45000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",1011477,['US'],en,karat kid legend,after famili tragedi kung fu prodigi li fong u...,750.3586,2025-05-08,104560790,94,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,when master unit new legaci begin,Karate Kid: Legends,False,7.281,367,"{'cast': [{'adult': False, 'gender': 2, 'id': ...","{'keywords': [{'id': 242, 'name': 'new york ci...",59560790.0,hit,132.357311,2025,Thursday,May,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [46]:
cast = df.drop(
    [
        "budget",
        "adult",
        "id",
        "revenue",
        "title",
        "video",
        "credits",
        "genres",
        "origin_country",
        "keywords",
        "spoken_languages",
        "original_title",
        "overview",
        "popularity",
        "status",
        "vote_average",
        "vote_count",
        "hit/flop",
        "profit_per",
        "box-off",
        "tagline",
        "runtime",
        "poster_path",
        "release_date",
        "original_language",
        "Unnamed: 0",
    ],
    axis=1,
)

In [48]:
X = cast.values

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(X)


def Recommend(movie):
    index = df[df["title"] == movie].index
    curr = similarity[index]
    top5 = np.argsort(curr)[0, :][::-1][1:6]
    return df[df.index.isin(top5)]["title"]


Recommend("Avatar")

244     Avatar: The Way of Water
741                       Aliens
5942        Dragonball Evolution
7025                   Australia
7558         The Absence of Eden
Name: title, dtype: object

In [51]:
import pickle

with open("../models/cast.pkl", "wb") as f:
    pickle.dump(similarity, f)

# Scale

In [3]:
df = pd.read_csv("../data/interim/scale.csv")

In [10]:
scale = df.drop(
    [
        "id",
        "genres",
        "adult",
        "origin_country",
        "spoken_languages",
        "original_title",
        "overview",
        "status",
        "release_date",
        "production_companies",
        "production_countries",
        "tagline",
        "title",
        "video",
        "runtime",
        "original_language",
        "credits",
        "keywords",
        "Unnamed: 0",
        "poster_path",
        "cast",
        "crew",
    ],
    axis=1,
)

In [11]:
scale.columns

Index(['budget', 'popularity', 'revenue', 'vote_average', 'vote_count',
       'box-off', 'hit/flop', 'profit_per'],
      dtype='object')

In [12]:
scale.head()

,budget,popularity,revenue,vote_average,vote_count,box-off,hit/flop,profit_per
0,4.500000e+07,750.3586,104560790,7.281,367,5.956079e+07,hit,132.357311
1,9.000000e+07,465.3293,131611905,7.453,944,4.161190e+07,hit,46.235450
2,2.250000e+08,498.0608,217000000,7.470,538,-8.000000e+06,flop,-3.555556
3,3.873155e+07,438.9744,0,7.015,97,-3.873155e+07,flop,-100.000000
4,3.873155e+07,425.9085,0,5.089,29,-3.873155e+07,flop,-100.000000

In [13]:
scale["budget"] = scale["budget"] / 1000000
scale["revenue"] = scale["revenue"] / 1000000
scale["box-off"] = scale["box-off"] / 1000000

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import (
    StandardScaler,
    MinMaxScaler,
    OneHotEncoder,
    OrdinalEncoder,
)

cf = ColumnTransformer(
    transformers=[
        ("ORencoding", OrdinalEncoder(), ["hit/flop"]),
        (
            "std",
            StandardScaler(),
            [
                "budget",
                "popularity",
                "revenue",
                "vote_average",
                "vote_average",
                "box-off",
                "profit_per",
            ],
        ),
    ],
    remainder="passthrough",
)

In [15]:
from sklearn.pipeline import Pipeline

ppl = Pipeline([("std", cf)])
X = ppl.fit_transform(scale)

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(X)


def Recommend(movie):
    index = df[df["title"] == movie].index
    curr = similarity[index]
    top5 = np.argsort(curr)[0, :][::-1][1:6]
    return df[df.index.isin(top5)]["title"]

In [17]:
Recommend("Interstellar")

152                  Inception
210                   Iron Man
229    The Wolf of Wall Street
295                  Gladiator
949             Now You See Me
Name: title, dtype: object

In [18]:
import pickle

with open("../models/scale.pkl", "wb") as f:
    pickle.dump(similarity, f)